with-expecter: true
inpackage: false
packages:
  custom-in-memory-db/internal/server/db/storage:
    interfaces:
      Storage:
        config:
          dir: "mocks/storage"
  custom-in-memory-db/internal/server/db/compute:
    interfaces:
      Compute:
        config:
          dir: "mocks/compute"
  custom-in-memory-db/internal/server/db/parser:
    interfaces:
      Parser:
        config:
          dir: "mocks/parser"
  custom-in-memory-db/internal/server/network:
    interfaces:
      Endpoint:
        config:
          dir: "mocks/network"