with-expecter: true
inpackage: true
packages:
  custom-in-memory-db/internal/server/db/storage:
    interfaces:
      Storage:
        config:
          dir: "mocks/storage"
  custom-in-memory-db/internal/server/db/compute:
    interfaces:
      Compute:
        config:
          dir: "mocks/compute"
  custom-in-memory-db/internal/server/db/wal:
    interfaces:
      WriterInterface:
        config:
          inpackage: false
          dir: "mocks/wal"
          outpkg: "walMock"
  io:
    interfaces:
      Reader:
        config:
          inpackage: false
          dir: "mocks/io"
          outpkg: "ioMock"