with-expecter: true
inpackage: true
packages:
  custom-in-memory-db/internal/server/storage:
    interfaces:
      Storage:
        config:
          dir: "mocks/storage"
  custom-in-memory-db/internal/server/compute:
    interfaces:
      Compute:
        config:
          dir: "mocks/compute"
  io:
    interfaces:
      Reader:
        config:
          inpackage: false
          dir: "mocks/io"
          outpkg: "ioMock"