// Code generated by mockery v2.46.0. DO NOT EDIT.

package compute

import (
	parser "custom-in-memory-db/internal/server/parser"

	mock "github.com/stretchr/testify/mock"
)

// MockCompute is an autogenerated mock type for the Compute type
type MockCompute struct {
	mock.Mock
}

type MockCompute_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCompute) EXPECT() *MockCompute_Expecter {
	return &MockCompute_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function with given fields: cmd
func (_m *MockCompute) Exec(cmd parser.Command) (string, error) {
	ret := _m.Called(cmd)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(parser.Command) (string, error)); ok {
		return rf(cmd)
	}
	if rf, ok := ret.Get(0).(func(parser.Command) string); ok {
		r0 = rf(cmd)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(parser.Command) error); ok {
		r1 = rf(cmd)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCompute_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockCompute_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - cmd parser.Command
func (_e *MockCompute_Expecter) Exec(cmd interface{}) *MockCompute_Exec_Call {
	return &MockCompute_Exec_Call{Call: _e.mock.On("Exec", cmd)}
}

func (_c *MockCompute_Exec_Call) Run(run func(cmd parser.Command)) *MockCompute_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(parser.Command))
	})
	return _c
}

func (_c *MockCompute_Exec_Call) Return(_a0 string, _a1 error) *MockCompute_Exec_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCompute_Exec_Call) RunAndReturn(run func(parser.Command) (string, error)) *MockCompute_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCompute creates a new instance of MockCompute. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCompute(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCompute {
	mock := &MockCompute{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
